DROP TABLE IF EXISTS FISIOTERAPEUTA CASCADE;
CREATE TABLE FISIOTERAPEUTA(
    	FIS_ID SERIAL PRIMARY KEY,
    	FIS_NOME VARCHAR(150) NOT NULL,
	FIS_DT_NASCIMENTO DATE NOT NULL,
	FIS_RG INTEGER NOT NULL,
	FIS_CPF VARCHAR(11) NOT NULL,
	FIS_EMAIL VARCHAR(100) NOT NULL,
	FIS_TELEFONE VARCHAR(12),
	FIS_DT_EXCLUSAO TIMESTAMP WITHOUT TIME ZONE,
	FIS_STATUS VARCHAR(10) NOT NULL,
	FIS_DT_ATUALIZACAO TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

INSERT INTO FISIOTERAPEUTA (FIS_NOME, FIS_DT_NASCIMENTO, FIS_RG, FIS_CPF, FIS_EMAIL, FIS_TELEFONE, FIS_DT_EXCLUSAO, FIS_STATUS) 
values('Fabricio', '1989-10-23', 5331666, '02762626110', 'fabriciosantana@gmail.com', '062992355707', null, 'Ativo');
