DROP TABLE IF EXISTS FISIOTERAPEUTA CASCADE;
CREATE TABLE FISIOTERAPEUTA(
    FIS_ID SERIAL PRIMARY KEY,
    FIS_NOME VARCHAR(150) NOT NULL,
	FIS_DT_NASCIMENTO DATE NOT NULL,
	FIS_RG INTEGER NOT NULL,
	FIS_CPF VARCHAR(11) NOT NULL,
	FIS_EMAIL VARCHAR(100) NOT NULL,
	FIS_TELEFONE VARCHAR(12),
	FIS_DT_INCLUSAO DATE NOT NULL,
	FIS_DT_EXCLUSAO DATE,
	FIS_STATUS VARCHAR(1) NOT NULL,
	FIS_PERFIL VARCHAR(3) NOT NULL
);

INSERT INTO FISIOTERAPEUTA (FIS_NOME, FIS_DT_NASCIMENTO, FIS_RG, FIS_CPF, FIS_EMAIL, FIS_TELEFONE, FIS_DT_INCLUSAO, FIS_DT_EXCLUSAO, FIS_STATUS, FIS_PERFIL) 
values('Fabricio', '1989-10-23', 5331666, '02762626110', 'fabriciosantana@gmail.com', '062992355707', '2021-06-07', null, 'A', 'ADM');
