DROP TABLE IF EXISTS SETOR_EMPRESA CASCADE;
CREATE TABLE SETOR_EMPRESA(
    SET_ID SERIAL PRIMARY KEY,
	SET_NOME VARCHAR(150) NOT NULL,
    SET_SIGLA VARCHAR(50) NOT NULL,
	SET_CLI_ID INTEGER NOT NULL,
    CONSTRAINT SET_CLI_FK FOREIGN KEY (SET_CLI_ID)
		REFERENCES CLIENTE(CLI_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO SETOR_EMPRESA(SET_NOME, SET_SIGLA, SET_CLI_ID)
VALUES ('TECNOLOGIA DA INFORMAÇÃO', 'TI', 1);