DROP TABLE IF EXISTS SETOR_EMPRESA CASCADE;
CREATE TABLE SETOR_EMPRESA(
    	SET_ID SERIAL PRIMARY KEY,
	SET_NOME VARCHAR(150) NOT NULL,
    	SET_SIGLA VARCHAR(50) NOT NULL,
	SET_CLI_ID INTEGER NOT NULL,
	SET_DT_ATUALIZACAO TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
	SET_STATUS VARCHAR(10) NOT NULL,
    	CONSTRAINT SET_CLI_FK FOREIGN KEY (SET_CLI_ID)
		REFERENCES CLIENTE(CLI_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO SETOR_EMPRESA(SET_NOME, SET_SIGLA, SET_CLI_ID, SET_STATUS)
VALUES ('TECNOLOGIA DA INFORMAÇÃO', 'TI', 1, 'Ativo');

INSERT INTO SETOR_EMPRESA(SET_NOME, SET_SIGLA, SET_CLI_ID, SET_STATUS)
VALUES ('SETOR JURÍDICO', 'SEJUR', 1, 'Ativo');

INSERT INTO SETOR_EMPRESA(SET_NOME, SET_SIGLA, SET_CLI_ID, SET_STATUS)
VALUES ('TECNOLOGIA DA INFORMAÇÃO', 'TI', 2, 'Ativo');

INSERT INTO SETOR_EMPRESA(SET_NOME, SET_SIGLA, SET_CLI_ID, SET_STATUS)
VALUES ('COMPRAS', 'SETCOMP', 2, 'Ativo');

INSERT INTO SETOR_EMPRESA(SET_NOME, SET_SIGLA, SET_CLI_ID, SET_STATUS)
VALUES ('GESTÃO DE PESSOAS', 'SETPES', 2, 'Ativo');

INSERT INTO SETOR_EMPRESA(SET_NOME, SET_SIGLA, SET_CLI_ID, SET_STATUS)
VALUES ('FINANCEIRO', 'SETFIN', 2, 'Ativo');

INSERT INTO SETOR_EMPRESA(SET_NOME, SET_SIGLA, SET_CLI_ID, SET_STATUS)
VALUES ('ATENDIMENTO', 'SAC', 1, 'Ativo');