DROP TABLE IF EXISTS COLABORADOR CASCADE;
CREATE TABLE COLABORADOR(
	COL_ID SERIAL PRIMARY KEY,
    COL_NOME VARCHAR(150) NOT NULL,
	COL_DT_NASCIMENTO DATE NOT NULL,
	COL_RG INTEGER NOT NULL,
	COL_CPF VARCHAR(11) NOT NULL,
	COL_EMAIL VARCHAR(100) NOT NULL,
	COL_TELEFONE VARCHAR(12),
	COL_DT_INCLUSAO DATE NOT NULL,
	COL_DT_EXCLUSAO DATE,
	COL_STATUS VARCHAR(1) NOT NULL,
	COL_SET_ID INTEGER NOT NULL,
	CONSTRAINT COL_SET_FK FOREIGN KEY (COL_SET_ID)
    	REFERENCES SETOR_EMPRESA(SET_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO COLABORADOR (COL_NOME, COL_DT_NASCIMENTO, COL_RG, COL_CPF, COL_EMAIL, COL_TELEFONE, COL_DT_INCLUSAO, COL_DT_EXCLUSAO, COL_STATUS, COL_SET_ID)
VALUES ('FABRICIO SANTANA', '1899-10-09', 1234567, '00100200345', 'fabricio.santana@hotmail.com', '62991223344', '2021-06-08', null, 'A', 1);