DROP TABLE IF EXISTS AVALIACAO CASCADE;
CREATE TABLE AVALIACAO(
    AVA_ID SERIAL PRIMARY KEY,
	AVA_DESCRICAO VARCHAR(500) NOT NULL,
    AVA_DT_HORA_AVALIACAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	AVA_FIS_ID INTEGER NOT NULL,
	AVA_COL_ID INTEGER NOT NULL,
    CONSTRAINT AVA_FIS_FK FOREIGN KEY (AVA_FIS_ID)
		REFERENCES FISIOTERAPEUTA(FIS_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT AVA_COL_FK FOREIGN KEY (AVA_COL_ID)
		REFERENCES COLABORADOR(COL_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO AVALIACAO (AVA_DESCRICAO, AVA_DT_HORA_AVALIACAO, AVA_FIS_ID, AVA_COL_ID)
VALUES ('Colaborador esta bem', '2021-06-09T09:00:00Z', 1, 1);

INSERT INTO AVALIACAO (AVA_DESCRICAO, AVA_DT_HORA_AVALIACAO, AVA_FIS_ID, AVA_COL_ID)
VALUES ('Colaborador esta mal', '2021-06-09T21:00:00Z', 1, 1);

INSERT INTO AVALIACAO (AVA_DESCRICAO, AVA_DT_HORA_AVALIACAO, AVA_FIS_ID, AVA_COL_ID)
VALUES ('Colaborador esta morto', '2021-06-09T01:00:00Z', 1, 1);