DROP TABLE IF EXISTS SESSAO_LABORAL CASCADE;
CREATE TABLE SESSAO_LABORAL(
    	SES_ID SERIAL PRIMARY KEY,
	SES_FIS_ID INTEGER NOT NULL,
	SES_CLI_ID INTEGER NOT NULL,
	CONSTRAINT SES_FIS_FK FOREIGN KEY (SES_FIS_ID)
		REFERENCES FISIOTERAPEUTA(FIS_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT SES_CLI_FK FOREIGN KEY (SES_CLI_ID)
		REFERENCES CLIENTE(CLI_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	SES_DT_HORA_SESSAO TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);


INSERT INTO SESSAO_LABORAL (SES_FIS_ID, SES_CLI_ID)
VALUES (1, 1);
/*
INSERT INTO SESSAO_LABORAL (SES_FIS_ID, SES_CLI_ID)
VALUES (1, 2);

INSERT INTO SESSAO_LABORAL (SES_FIS_ID, SES_CLI_ID)
VALUES (1, 2);
*/