DROP TABLE IF EXISTS SESSAO_LABORAL CASCADE;
CREATE TABLE SESSAO_LABORAL(
    SES_ID SERIAL PRIMARY KEY,
    SES_DT_HORA_SESSAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	SES_FIS_ID INTEGER NOT NULL,
	SES_AVA_ID INTEGER NOT NULL,
    CONSTRAINT SES_FIS_FK FOREIGN KEY (SES_FIS_ID)
		REFERENCES FISIOTERAPEUTA(FIS_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT SES_AVA_FK FOREIGN KEY (SES_AVA_ID)
		REFERENCES AVALIACAO(AVA_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);


INSERT INTO SESSAO_LABORAL (SES_DT_HORA_SESSAO, SES_FIS_ID, SES_AVA_ID)
VALUES ('2021-06-09T09:00:00Z', 1, 1);

INSERT INTO SESSAO_LABORAL (SES_DT_HORA_SESSAO, SES_FIS_ID, SES_AVA_ID)
VALUES ('2021-06-09T21:00:00Z', 1, 2);

INSERT INTO SESSAO_LABORAL (SES_DT_HORA_SESSAO, SES_FIS_ID, SES_AVA_ID)
VALUES ('2021-06-09T01:00:00Z', 1, 3);