DROP TABLE IF EXISTS AVALIACAO CASCADE;
CREATE TABLE AVALIACAO(
    	AVA_ID SERIAL PRIMARY KEY,
	AVA_DESCRICAO VARCHAR(500) NOT NULL,
    	AVA_DT_HORA_AVALIACAO TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
	AVA_FIS_ID INTEGER NOT NULL,
	AVA_COL_ID INTEGER NOT NULL,
	AVA_SES_ID INTEGER NOT NULL,
    	CONSTRAINT AVA_FIS_FK FOREIGN KEY (AVA_FIS_ID)
		REFERENCES FISIOTERAPEUTA(FIS_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT AVA_SES_FK FOREIGN KEY (AVA_SES_ID)
		REFERENCES SESSAO_LABORAL (SES_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT AVA_COL_FK FOREIGN KEY (AVA_COL_ID)
		REFERENCES COLABORADOR(COL_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
/*
INSERT INTO AVALIACAO (AVA_DESCRICAO, AVA_FIS_ID, AVA_COL_ID, AVA_SES_ID)
VALUES ('Colaborador esta bem', 1, 1, 1);

INSERT INTO AVALIACAO (AVA_DESCRICAO, AVA_FIS_ID, AVA_COL_ID, AVA_SES_ID)
VALUES ('Colaborador esta mal', 1, 1, 1);

INSERT INTO AVALIACAO (AVA_DESCRICAO, AVA_FIS_ID, AVA_COL_ID, AVA_SES_ID)
VALUES ('Colaborador esta morto', 1, 1, 1);
*/