DROP TABLE IF EXISTS PARTICIPACAO CASCADE;
CREATE TABLE PARTICIPACAO(
    	PAR_ID SERIAL PRIMARY KEY,
	PAR_FREQUENCIA BOOLEAN NOT NULL,
    	PAR_DT_FREQUENCIA  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
	PAR_JUSTIFICATIVA VARCHAR(100),
	PAR_SES_ID INTEGER NOT NULL,
	PAR_COL_ID INTEGER NOT NULL,
	PAR_SET_ID INTEGER NOT NULL,
    	CONSTRAINT PAR_SES_FK FOREIGN KEY (PAR_SES_ID)
		REFERENCES SESSAO_LABORAL(SES_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT PAR_COL_FK FOREIGN KEY (PAR_COL_ID)
		REFERENCES COLABORADOR(COL_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT PAR_SET_FK FOREIGN KEY (PAR_SET_ID)
		REFERENCES SETOR_EMPRESA(SET_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

/*
INSERT INTO PARTICIPACAO (PAR_FREQUENCIA, PAR_DT_FREQUENCIA, PAR_JUSTIFICATIVA, PAR_SES_ID, PAR_COL_ID, PAR_SET_ID)
VALUES (TRUE, '2021-09-23', null, 1, 1, 1);
*/