DROP TABLE IF EXISTS PARTICIPACAO CASCADE;
CREATE TABLE PARTICIPACAO(
    PAR_ID SERIAL PRIMARY KEY,
	PAR_FREQUENCIA BOOLEAN NOT NULL,
    PAR_DT_HORA_FREQUENCIA TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PAR_JUSTIFICATIVA VARCHAR(100),
	PAR_SES_ID INTEGER NOT NULL,
	PAR_COL_ID INTEGER NOT NULL,
    CONSTRAINT PAR_SES_FK FOREIGN KEY (PAR_SES_ID)
		REFERENCES SESSAO_LABORAL(SES_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT PAR_COL_FK FOREIGN KEY (PAR_COL_ID)
		REFERENCES COLABORADOR(COL_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);


INSERT INTO PARTICIPACAO (PAR_FREQUENCIA, PAR_DT_HORA_FREQUENCIA, PAR_JUSTIFICATIVA, PAR_SES_ID, PAR_COL_ID)
VALUES (TRUE, '2021-06-09T09:00:00Z', null, 1, 1);

INSERT INTO PARTICIPACAO (PAR_FREQUENCIA, PAR_DT_HORA_FREQUENCIA, PAR_JUSTIFICATIVA, PAR_SES_ID, PAR_COL_ID)
VALUES (FALSE, '2021-06-09T09:00:00Z', null, 1, 1);

INSERT INTO PARTICIPACAO (PAR_FREQUENCIA, PAR_DT_HORA_FREQUENCIA, PAR_JUSTIFICATIVA, PAR_SES_ID, PAR_COL_ID)
VALUES (TRUE, '2021-06-09T09:00:00Z', null, 2, 1);

INSERT INTO PARTICIPACAO (PAR_FREQUENCIA, PAR_DT_HORA_FREQUENCIA, PAR_JUSTIFICATIVA, PAR_SES_ID, PAR_COL_ID)
VALUES (FALSE, '2021-06-09T09:00:00Z', null, 2, 1);
