DROP TABLE IF EXISTS ATENDIMENTO CASCADE;
CREATE TABLE ATENDIMENTO(
	ATE_ID SERIAL PRIMARY KEY,
    ATE_DT_HORA_ATENDIMENTO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	ATE_FIS_ID INTEGER NOT NULL,
	ATE_CLI_ID INTEGER NOT NULL,
    CONSTRAINT ATE_FIS_FK FOREIGN KEY (ATE_FIS_ID)
		REFERENCES FISIOTERAPEUTA(FIS_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ATE_CLI_FK FOREIGN KEY (ATE_CLI_ID)
		REFERENCES CLIENTE(CLI_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO ATENDIMENTO (ATE_DT_HORA_ATENDIMENTO, ATE_FIS_ID, ATE_CLI_ID)
VALUES ('2021-06-09T09:00:00Z', 1, 1);

INSERT INTO ATENDIMENTO (ATE_DT_HORA_ATENDIMENTO, ATE_FIS_ID, ATE_CLI_ID)
VALUES ('2021-06-10T09:00:00Z', 1, 1);