DROP TABLE IF EXISTS USUARIO CASCADE;
CREATE TABLE USUARIO(
	USU_LOGIN VARCHAR(14) PRIMARY KEY, 	
	SENHA VARCHAR(1000) NOT NULL,
	USU_DT_HORA_ATUALIZACAO TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
	USU_STATUS BOOLEAN NOT NULL	
);


INSERT INTO USUARIO  (USU_LOGIN, SENHA, USU_STATUS)
VALUES ('02762626110', '$2a$10$RtY.pxOg7TOfLEACdc0ddOkJFNPEOiY0KAD2PG0GMseaOSExFsqNC', true);

INSERT INTO USUARIO  (USU_LOGIN, SENHA, USU_STATUS)
VALUES ('00934392102', '$2a$10$RtY.pxOg7TOfLEACdc0ddOkJFNPEOiY0KAD2PG0GMseaOSExFsqNC', false);
