DROP TABLE IF EXISTS USUARIO_ROLE CASCADE;
CREATE TABLE USUARIO_ROLE (
	USUARIO_ID varchar(14) PRIMARY KEY,
	ROLE_ID varchar(10) NOT NULL,
	USR_NOME VARCHAR(200) NOT NULL,
	USR_STATUS BOOLEAN NOT NULL,
	USR_EMAIL VARCHAR(100) NOT NULL,
	USR_DT_HORA_ATUALIZACAO TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
	CONSTRAINT ROLE_FK FOREIGN KEY (ROLE_ID)
		REFERENCES ROLE (NOME_ROLE) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT USU_ROL_FK FOREIGN KEY (USUARIO_ID)
		REFERENCES USUARIO (USU_LOGIN) ON DELETE RESTRICT ON UPDATE CASCADE
);

insert into usuario_role (usuario_id, role_id, USR_NOME, USR_STATUS, USR_EMAIL) 
values ('02762626110','ROLE_ADM', 'Fabricio Santana', true, 'fabrisantana@outlook.com');

insert into usuario_role (usuario_id, role_id, USR_NOME, USR_STATUS, USR_EMAIL) 
values ('00934392102','ROLE_ADM', 'Matheus', true, 'matheus@outlook.com');